# Generated by Django 3.0.5 on 2020-08-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200828_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
